# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Probador CombustiblePy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3
      uses: actions/setup-python@v3
      with:
        python-version: "3"
    - name: Otorgar Permisos
      run: |
        chmod +x ./calcular.py
    - name: Probar script
      run: |
       ./calcular.py -p 1199 "ars" -d 637 "km" --rend 5 "km por cada litro" -t 0 "ars" >> costos.html
    - name: VERIFICAR SALIDA
      run: |
        cat costos.html && cp costos.html ../CombustiblePy
